### ISSUE TITLE
[JOSS Review] Consistent internal representations and vectorized operations

### ISSUE THREAD

**Issue by eliotwrobson** [thraraujo/pysymmpol#3]
Many of the internal data representations used in the library store coefficients using unannotated `tuple`s, see here https://github.com/thraraujo/pysymmpol/blob/main/pysymmpol/partitions/young.py#L26

You have numpy as a dependency, so I think it would be beneficial to switch the internal representation to use numpy vectors instead of tuples. Then, other internal operations can be implemented using fast vectorized operations in numpy, see: https://github.com/thraraujo/pysymmpol/blob/main/pysymmpol/polynomials/hall.py#L66

Similarly, library functions should accept numpy arrays as arguments to avoid unnecessary data conversions that can slow down these operations.

From review https://github.com/openjournals/joss-reviews/issues/6724

**Comment by thraraujo** [comment]
I'm going to start working on this issue today. There are a couple of functions that I want to modify slightly, so I'll get started on that. It might take me 1 or 2 days to complete.

P.S. In the tests, there's a special case for the Schur functions tests where we calculate the Schur polynomials for 15 and 16 boxes twice each. This is why it's slow.

**Comment by thraraujo** [comment]
Dear @eliotwrobson,

Thanks for your insightful suggestions; I have worked on them.

1. I've decided to maintain tuples as the default structure for user interaction. While internally utilizing numpy methods, the package's interface remains primarily pure Python, with potential integration of sympy. I appreciate the immutability and the clarity of input and output formats that tuples offer. However, I've heeded your advice to some extent by now allowing the use of numpy arrays.

2. Your point about utilizing numpy arrays for performance enhancement is well taken. I've begun integrating numpy arrays in certain sections of the code, such as the transpose method and within the states module. The latter, being pivotal to the package's functionality in physics, now incorporates numpy arrays in strategic areas. Additionally, I'm considering reimplementing this module in a faster language for long-term efficiency goals, aiming to handle all combinatorics in C while utilizing the package for symbolic polynomial manipulations.

3. I've optimized some methods to minimize nested 'for loops'. For instance, the method for calculating diagonal elements now employs arrays and requires only one 'for loop.' Similarly, enhancements have been made to the contains and interlaces methods within the Young module, significantly reducing computational overhead by terminating at the first encountered false condition rather than iterating through all possibilities.

4. Regarding the Hall-Littlewood polynomials example you mentioned, I adopt dictionaries instead of tuples to address efficiency concerns. Although it slightly streamlined the code and improved readability, it poses algorithmic challenges, particularly in efficiently iterating over coordinates and permutations. While I currently favor this approach, I remain open to exploring alternative strategies, especially as I consider implementing other polynomial types like MacDonald and Jack **in the future**.

5. I've updated the readme to include valuable references on relevant topics, including the books you recommended.

**Comment by eliotwrobson** [comment]
@thraraujo your changes look awesome, thanks for addressing them so quickly! For context, this issue was mainly meant to draw your attention to potential easy performance gains (especially if your package gets used on larger inputs), rather than a call to do a larger refactoring right away, and I think the changes you have incorporated have more than capitalized on that so far. This was never meant to be a review blocker either, so I will go ahead and close. One short comment on one of your items:

> Additionally, I'm considering reimplementing this module in a faster language for long-term efficiency goals, aiming to handle all combinatorics in C while utilizing the package for symbolic polynomial manipulations.

This is actually the reason I mentioned using numpy arrays in more places in the first place. Instead of reimplementing in C, if performance becomes an issue, you could consider converting substantial parts of your package to Cython and adding a compilation step to the package building: https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html

Cython integrates very cleanly with code that heavily uses Numpy, so it makes sense to have an eye towards using it where possible now if that conversion is something you'd be interested in later. As they say, premature optimization is the root of all evil, so I'd suggest not taking the plunge on this quite yet if you don't find yourself needing it.
